In [52]:
# !pip install pandas
# !pip install numpy

#Mode

'''Syntax

Description

‘r’

'r'

Read mode. Opens an existing file for reading. Raises an error if the file doesn't exist.

‘w’

'w'

Write mode. Creates a new file for writing. Overwrites the file if it already exists.

‘a’

'a'

Append mode. Opens a file for appending data. Creates the file if it doesn't exist.

‘x’

'x'

Exclusive creation mode. Creates a new file for writing but raises an error if the file already exists.

‘rb’

'rb'

Read binary mode. Opens an existing binary file for reading.

‘wb’

'wb'

Write binary mode. Creates a new binary file for writing.

‘ab’

'ab'

Append binary mode. Opens a binary file for appending data.

‘xb’

'xb'

Exclusive binary creation mode. Creates a new binary file for writing but raises an error if it already exists.

‘rt’

'rt'

Read text mode. Opens an existing text file for reading. (Default for text files)

‘wt’

'wt'

Write text mode. Creates a new text file for writing. (Default for text files)

‘at’

'at'

Append text mode. Opens a text file for appending data. (Default for text files)

‘xt’

'xt'

Exclusive text creation mode. Creates a new text file for writing but raises an error if it already exists.

‘r+’

'r+'

Read and write mode. Opens an existing file for both reading and writing.

‘w+’

'w+'

Write and read mode. Creates a new file for reading and writing. Overwrites the file if it already exists.

‘a+’

'a+'

Append and read mode. Opens a file for both appending and reading. Creates the file if it doesn't exist.

‘x+’

'x+'

Exclusive creation and read/write mode. Creates a new file for reading and writing but raises an error if it already exists'''

"Syntax\n\nDescription\n\n‘r’\n\n'r'\n\nRead mode. Opens an existing file for reading. Raises an error if the file doesn't exist.\n\n‘w’\n\n'w'\n\nWrite mode. Creates a new file for writing. Overwrites the file if it already exists.\n\n‘a’\n\n'a'\n\nAppend mode. Opens a file for appending data. Creates the file if it doesn't exist.\n\n‘x’\n\n'x'\n\nExclusive creation mode. Creates a new file for writing but raises an error if the file already exists.\n\n‘rb’\n\n'rb'\n\nRead binary mode. Opens an existing binary file for reading.\n\n‘wb’\n\n'wb'\n\nWrite binary mode. Creates a new binary file for writing.\n\n‘ab’\n\n'ab'\n\nAppend binary mode. Opens a binary file for appending data.\n\n‘xb’\n\n'xb'\n\nExclusive binary creation mode. Creates a new binary file for writing but raises an error if it already exists.\n\n‘rt’\n\n'rt'\n\nRead text mode. Opens an existing text file for reading. (Default for text files)\n\n‘wt’\n\n'wt'\n\nWrite text mode. Creates a new text file for writing. (Default for text files)\n\n‘at’\n\n'at'\n\nAppend text mode. Opens a text file for appending data. (Default for text files)\n\n‘xt’\n\n'xt'\n\nExclusive text creation mode. Creates a new text file for writing but raises an error if it already exists.\n\n‘r+’\n\n'r+'\n\nRead and write mode. Opens an existing file for both reading and writing.\n\n‘w+’\n\n'w+'\n\nWrite and read mode. Creates a new file for reading and writing. Overwrites the file if it already exists.\n\n‘a+’\n\n'a+'\n\nAppend and read mode. Opens a file for both appending and reading. Creates the file if it doesn't exist.\n\n‘x+’\n\n'x+'\n\nExclusive creation and read/write mode. Creates a new file for reading and writing but raises an error if it already exists"

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
from nba_api.stats.endpoints import leaguegamefinder
import os
from PIL import Image
from IPython.display import IFrame

In [30]:
dict = {"a":[11,12,13],"b":[45,56,78]}

In [31]:
df = pd.DataFrame(dict)
df

    a   b
0  11  45
1  12  56
2  13  78

In [32]:
df.head()

    a   b
0  11  45
1  12  56
2  13  78

In [33]:
df.mean()

a    12.000000
b    59.666667
dtype: float64

In [34]:
def one_dict(list_dict):
    keys = list_dict[0].keys()
    out_dict ={key:[] for key in keys}
    for dict_ in list_dict:
        for key, value in dict_.items():
            out_dict[key].append(value)
    return out_dict

In [39]:
url = 'https://www.ibm.com/'
r = requests.get(url)
r.status_code
print(r.request.headers)

{'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Cookie': '_abck=19761B38BE543C6A495804429B7A1C72~-1~YAAQzvUwF6IipDGfAQAA51CjURCKwTPFVPbBP+4OYCm9cF3nD42xl+/ALaAFZIkUtIHfaeMSzqrfgaOjdxaKsz42EdVkVaeea8xj8Ozb2STDAfgswnzufOkLrHo/7iyPAdL09IUNrmSDrGVDm60HNYtM+/daocDJGUZLlNaj4stf0AgNgT9gkc99ruVrfU3SGajGFNoB5PFfUpyUb15HFtqOWgbwI44hDJ8NYp5kLxaYoYGzHJZ79dC0QzoGjSXxYfqEFsDRrobIombBvP4LQ5rnrkI2JPhfCkciZke45M6yN5XH1/1JTlgSVuFOWQss7LJ7RmM6XGvkYosOdMJfSqW6iNoCHXZB9i8vPwP4mgqYjZfpKHDmeLsSEbBYLM/EKMVSgTzkD49B46fH/MM19mWjku1aY4zI5Sb/lpSLrX8iJ61W0kZrSu5w3yihaWchny0=~-1~-1~-1~-1~-1; bm_sz=A254A0841FE65ED3A226862C0642EBA2~YAAQzvUwF6MipDGfAQAA51CjUQAM5v3cqnHccScdHmztcG7n4z/2pwdqOVHoJDQT0N5FiGykcnWYOzJsl1G+WPCXy6ffaMFZaiKUfmHw0hCmiL8aIE76iOYsEVjpXqDrEfygqGSNEI9Qagan8jbj+DScCOyPyB43plGNYh+AUJy3npIPK2uWqOGJUBIWs5tBBo/P6lbqybnewwpVLd2JDNSYe4oh8Izd6wBOLiO4gsxS8W58qs6xoCPjXIcnP4NjLgSd03x5aPDW6nlvbCBPLNLtShJufcqd5E9X7FXcTqX+gcOh0LEkpw/n9kFnooJety33G7evCjwF0EoP2HOtgVU1yZ/SIj9bCiRw4K4XSJbiiQelTPoysNwdHMCaNDrptIQ50w==~3360308~4277062'}

In [40]:
print(r.request.body)

None

In [41]:
headers = r.headers
print(headers)

{'Content-Security-Policy': 'upgrade-insecure-requests', 'x-frame-options': 'SAMEORIGIN', 'Last-Modified': 'Sat, 11 Jul 2026 14:12:43 GMT', 'ETag': '"30e7e-65656736062bd-gzip"', 'Accept-Ranges': 'bytes', 'Content-Type': 'text/html;charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'max-age=600', 'Expires': 'Sat, 11 Jul 2026 14:54:45 GMT', 'X-Akamai-Transformed': '0 - 0 -', 'Content-Encoding': 'gzip', 'Date': 'Sat, 11 Jul 2026 14:44:45 GMT', 'Content-Length': '41322', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Strict-Transport-Security': 'max-age=31536000'}

In [42]:
headers['Date']

'Sat, 11 Jul 2026 14:44:45 GMT'

In [43]:
headers['Content-Type']

'text/html;charset=utf-8'

In [44]:
r.encoding

'utf-8'

In [45]:
r.text[0:100]

' \n<!DOCTYPE HTML>\n\n<html lang="en">\n<head>\r\n    \r\n      \r\n    \r\n    \r\n    \r\n    \r\n    \r\n    \r\n      '

In [46]:
url2 = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/IDSNlogo.png'

In [47]:
r = requests.get(url2)

In [48]:
print(r.headers)

{'Date': 'Sat, 11 Jul 2026 14:52:00 GMT', 'X-Clv-Request-Id': '5fcb135d-2bbd-4021-99ec-8d3c097e7087', 'Server': 'Cleversafe', 'X-Clv-S3-Version': '2.5', 'Accept-Ranges': 'bytes', 'x-amz-request-id': '5fcb135d-2bbd-4021-99ec-8d3c097e7087', 'ETag': '"8bb44578fff8fdcc3d2972be9ece0164"', 'Content-Type': 'image/png', 'Last-Modified': 'Wed, 16 Nov 2022 03:32:41 GMT', 'Content-Length': '78776'}

In [49]:
r.headers['Content-Type']

'image/png'

### An image is a response object that contains the image as a bytes-like object. As a result, we must save it using a file object. First, we specify the file path and name

In [50]:
path = os.path.join(os.getcwd(),'image.png')

### We save the file, in order to access the body of the response we use the attribute content then save it using the open function and write method:

In [54]:
with open(path,'wb') as f:
    f.write(r.content)